# Generated by Django 4.2.16 on 2025-04-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language_direction', models.CharField(choices=[('en_tr', 'English - Turkish'), ('tr_en', 'Turkish - English')], default='en_tr', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_word', models.CharField(max_length=100)),
                ('target_word', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='words.wordlist')),
            ],
        ),
    ]
